## semantic-release config
# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/circleci-workflows.md

version: '2.1'
orbs:
  node: circleci/node@4.2.1
  # node: circleci/python:3-node
jobs:
  test:
    docker:
      - image: circleci/python:3-node
    #   - image: cimg/python:3.9.2
    #   - image: circleci/node@4.2.1
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test:ci
          name: Run YARN tests
      - store_test_results:
          path: test-results
  release:
    executor: node/default
    steps:
      - checkout
      - node/install:
          lts: true
      - node/install-packages # Install and automatically cache packages
      # Run optional required steps before releasing
      # - run: npm run build-script
      - run: npx semantic-release
workflows:
  unit-tests:
    jobs:
      - test
  test-and-release:
    jobs: 
      - node/test:
          matrix:
            parameters:
              version:
                - 16.13.2
      - release:
          requires:
            - node/test