## semantic-release config
# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/circleci-workflows.md

version: '2.1'
orbs:
  node: circleci/node@5.0.0
  # node: circleci/node@4.2.1
  # node: circleci/python:3-node
jobs:
  test:
    docker:
      - image: circleci/python:3-node
    #   - image: cimg/python:3.9.2
    #   - image: circleci/node@4.2.1
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test:ci
          name: Run YARN tests
      - store_test_results:
          path: test-results
  release:
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      #     lts: true
      # - node/install-packages # Install and automatically cache packages
      # Run optional required steps before releasing
      # - run: npm run build-script
      - run: npx semantic-release
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3-node
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Install dpkg and fakeroot
          command: |
            sudo apt-get update -y
            sudo apt-get install -y dpkg fakeroot
      - run:
          name: Generate Builds
          command: yarn make
      - store_artifacts:
          path: ~/repo/out/make
  publish:
    docker:
      - image: circleci/python:3-node
    executor: node/default
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Publish Builds
          command: yarn run publish
workflows:
  test-and-release:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: /main\/.*/
  # build-and-publish:
  #   jobs:
  #     - build
  #     - publish:
  #         requires:
  #           - build