# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test

version: '2.1'
orbs:
  node: circleci/node@4.2.1
  # node: circleci/python:3-node
jobs:
  test:
    docker:
      - image: circleci/python:3-node
    #   - image: cimg/python:3.9.2
    #   - image: circleci/node@4.2.1
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test:ci
          name: Run YARN tests
      - store_test_results:
          path: test-results
workflows:
  unit-tests:
    jobs:
      - test